# Generated by Django 4.2.3 on 2023-07-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_content_en_post_content_ru_post_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_ru',
            new_name='content_uz',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='description_ru',
            new_name='description_uz',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_ru',
            new_name='title_uz',
        ),
    ]
