# Generated by Django 4.2.3 on 2023-07-26 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_rename_content_ru_post_content_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views_count',
        ),
        migrations.CreateModel(
            name='ViewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewpost', to='post.post', verbose_name="Ko'rganlar soni")),
            ],
            options={
                'unique_together': {('post', 'device')},
            },
        ),
    ]
